# Environment: macOS
# =============================================================================

export DEV="$HOME/Developer"
export MACHINE="$DEV/machine"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"

# global environment variables
source "$MACHINE/config/shell/env.sh"
