# Environment (shared across machines)
# =============================================================================

export ZSH="$HOME/.zsh/omz"    # oh-my-zsh path
export EDITOR="$(which nvim)"  # default to neovim as the editor
export LESS="-R --ignore-case" # use less with colors and case-insensitivity
export SYSTEMD_LESS=$LESS      # less arguments of systemd pager
export BAT_PAGER="less $LESS"  # use less as the pager for bat
