#!/usr/bin/env zsh

# notebook and iCloud directories
iCloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
Notebook="$iCloud/Notebook"
Music="$HOME/Music/Personal"
# open notebook with vscode
alias notes='code $Notebook'

# exa
alias le="exa -a --git --group-directories-first"
alias lle="exa -a --git --group-directories-first -lh"

# download video from URL
function dl-video {
    dir=("-d" "$HOME/Downloads")
    zparseopts -D -K -- d:=dir

    youtube-dl --write-sub --write-auto-sub --embed-subs \
        --merge-output-format mp4 -o "${dir[2]}/%(title)s.%(ext)s" $1
}

# download audio from URL
function dl-audio {
    dir=("-d" "$HOME/Downloads")
    zparseopts -D -K -- d:=dir

    youtube-dl -x --audio-format mp3 -o "${dir[2]}/%(title)s.%(ext)s" $1
}
