#!/usr/bin/env zsh

# notebook's directory
notebook="$HOME/Notebook"
# open notebook with vscode
alias notes='code $notebook'

# colorized ls
alias lc='colorls -A --sd --git-status'

# complete uninstallation of casks
alias uninstall='brew uninstall --zap --force'

# download YouTube video
alias dlyoutube='youtube-dl --write-sub --write-auto-sub --embed-subs \
    --merge-output-format mp4 -o "$HOME/Downloads/%(title)s.%(ext)s"'

# open manpage in Preview app
alias mp='man-preview'
