#!/usr/bin/env zsh

# uninstall homebrew package with its dependencies
function uninstall {
    brew uninstall $1
    brew autoremove
    brew cleanup
}

# download video from URL
function dl-video {
    usage="usage: $0 [-a] URL [dir]"
    audio=false
    dir="${HOME}/Downloads"

    if [[ $1 == '-a' ]] ; then
        audio=true
        shift
    fi

    if (($# == 2)) ; then
        if [[ ! -d $2 ]] ; then
            echo "\033[0;31mERROR:\033[0m '$2' is not a valid directory."
            return 1
        fi
        dir=$2
    elif (($# != 1)) ; then
        echo $usage
        return 1
    fi

    sub=(--write-sub --write-auto-sub --sub-lang en --embed-subs)
    cmd=(--embed-thumbnail --add-metadata -o "$dir/%(title)s.%(ext)s")
    if [[ $audio != true ]] ; then
        youtube-dl $sub $cmd --merge-output-format mp4 $1
    else
        youtube-dl -x $cmd --audio-format mp3 $1
    fi
}
