export DEV="$HOME/Developer"
export DOTFILES="$DEV/dotfiles"

# base directory relative to which user data files should be stored
export XDG_DATA_HOME="$DEV/data"
# base directory relative to which user configuration files should be stored
export XDG_CONFIG_HOME="$DEV/config"
# base directory relative to which cache files should be stored
export XDG_CACHE_HOME="$DEV/cache"

# zsh and oh-my-zsh directories
export ZDOTDIR="$XDG_CONFIG_HOME"
export ZSH="$XDG_DATA_HOME/oh-my-zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump-${ZSH_VERSION}"
export SHELL_SESSIONS_DISABLE=1

# default editor
export EDITOR=/usr/local/bin/code
export VISUAL=/usr/local/bin/code

# vscode extensions folder
export VSCODE_EXTENSIONS="$XDG_DATA_HOME/vscode/extensions"

# python
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
