# theme
ZSH_THEME="common"

# plugins
plugins=(
    colored-man-pages # adds colors to man pages
    osx               # provides a few utilities on macOS
)

# zsh
export HISTFILE="$XDG_DATA_HOME/zsh/zsh_history"
# homebrew
export PATH="/usr/local/sbin:$PATH"
# asdf
. $(brew --prefix asdf)/libexec/asdf.sh

# load aliases
source $ZDOTDIR/.aliases
# load functions
source $ZDOTDIR/.functions

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh
# load zsh syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
