# theme
ZSH_THEME="common"

# plugins
plugins=(
    colored-man-pages # adds colors to man pages
    osx               # provides a few utilities on macOS
)

# zsh
export HISTFILE="$XDG_DATA_HOME/zsh/history"
setopt CORRECT_ALL # offer to correct commands and arguments
source $ZDOTDIR/.aliases
source $ZDOTDIR/.lazy_loader

# homebrew
export PATH="/usr/local/sbin:$PATH"

# add brew's python to path
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
# lazy load pyenv. Execute pyenv to load
if [[ -d "/usr/local/Cellar/pyenv" ]] ; then
    pyenv_init() { eval "$(pyenv init -)" }
    lazy_load pyenv_init pyenv

fi

# add brew's ruby and its gems to path
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"
# lazy load rbenv. Execute rbenv to load
if [[ -d "/usr/local/Cellar/rbenv" ]] ; then
    rbenv_init() { eval "$(rbenv init -)" }
    lazy_load rbenv_init rbenv
fi

# lazy load nvm. Execute nvm to load
if [[ -d "/usr/local/Cellar/nvm" ]] ; then
    nvm_init() {
        . /usr/local/opt/nvm/nvm.sh
        . /usr/local/opt/nvm/etc/bash_completion.d/nvm
    }
    lazy_load nvm_init nvm
fi

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh
# load zsh syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
