# Environment: Raspberry Pi
# =============================================================================

export PURE="$HOME/.zsh/pure"
export ZSHCOMP="$HOME/.zsh/zsh-completions"

# global environment variables
shell_config="$(dirname $(realpath ~/.zshenv))"
source "$shell_config/zsh_env.sh"
