# Environment: Raspberry Pi
# =============================================================================

export MACHINE="$HOME/machine"
export PURE="$HOME/.zsh/pure"
export ZSHCOMP="$HOME/.zsh/zsh-completions"
export TAILSCALE_DEVICEID=
export TAILSCALE_IP=

# global environment variables
source "$MACHINE/zsh_env.sh"
