services:
  tailscale:
    image: tailscale/tailscale:latest
    network_mode: "host" # use the host's network stack
    environment:
      - TS_AUTH_ONCE=true # authenticate only once
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY} # Tailscale auth key
      - TS_STATE_DIR=/var/lib/tailscale # directory for Tailscale state
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale # persist Tailscale state
      - /dev/net/tun:/dev/net/tun # provide TUN device for network tunneling
    restart: unless-stopped # ensure Tailscale restarts automatically
