# Environment: macOS
# =============================================================================

export DEV="$HOME/Developer"
export MACHINE="$DEV/machine"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export PRIVATE_MACHINE="$ICLOUD/.machine"

# global environment variables
source "$MACHINE/config/shell/zshenv"
# private environment variables
source "$PRIVATE_MACHINE/env.sh"

export GODOT_PATH="/Applications/Godot_mono.app/Contents/MacOS/Godot"
