# Environment: macOS
# =============================================================================

export DEV="$HOME/Developer"
export MACHINE="$DEV/machine"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export PRIVATE_MACHINE="$ICLOUD/.machine"
export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"

# XDG Base Directory Specification
export XDG_DATA_HOME="$HOME/Library/Application Support"
export XDG_CONFIG_HOME="$HOME/Library/Application Support"
export XDG_STATE_HOME="$HOME/Library/Application Support"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export XDG_RUNTIME_DIR="$HOME/Library/Application Support"
export XDG_DATA_DIRS="/Library/Application Support"
export XDG_CONFIG_DIRS="$HOME/Library/Preferences"
export XDG_CONFIG_DIRS="$XDG_CONFIG_DIRS:/Library/Application Support"
export XDG_CONFIG_DIRS="$XDG_CONFIG_DIRS:/Library/Preferences"

# global environment variables
source "$MACHINE/config/shell/zshenv"
# private environment variables
source "$PRIVATE_MACHINE/env.sh"
