# Environment: macOS
# =============================================================================

# global environment variables
source $(realpath "$(readlink "$HOME/.zshenv")/../../../../config/zshenv")

# machine specific environment variables
export DEV="$HOME/Developer"
export ICLOUD="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
export GODOT_PATH="/Applications/Godot_mono.app/Contents/MacOS/Godot"
