#!/usr/bin/env zsh

# directories
iCloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
Notebook="$iCloud/Notebook"
Projects="$iCloud/Projects"

alias notes='code $Notebook' # open notebook in vscode
alias rsh='exec zsh -l'      # reset current shell session

# exa
alias le='exa --group-directories-first --icons --sort=Name'
alias lte='le -T -L'
alias lle='le -hlmU --git --no-user'
alias llte='lle -T -L'
