export DEV="$HOME/Developer"
export DOTFILES="$DEV/dotfiles"

# XDG base directories
export XDG_CONFIG_HOME="$DEV/config"
export XDG_CACHE_HOME="$DEV/cache"
export XDG_DATA_HOME="$DEV/data"
export XDG_STATE_HOME="$DEV/state"
export XDG_RUNTIME_DIR="$DEV/runtime"

# default editor
export EDITOR=/usr/local/bin/code
export VISUAL=/usr/local/bin/code

# zsh and oh-my-zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH="$XDG_DATA_HOME/oh-my-zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump-${ZSH_VERSION}"
export SHELL_SESSIONS_DISABLE=1

# gpg for git commit signing
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GPG_TTY="$(tty)"

source $ZDOTDIR/env_vars
