export DEV="$HOME/Developer"
export DOTFILES="$DEV/dotfiles"

# XDG base directories
export XDG_CONFIG_HOME="$HOME/Library/Application Support"
export XDG_CACHE_HOME="$HOME/Library/Caches"
export XDG_DATA_HOME="$HOME/Library/Application Support"
export XDG_STATE_HOME="$HOME/Library/Application Support"

export XDG_RUNTIME_DIR="$HOME/Library/Application Support"
export XDG_DATA_DIRS="/Library/Application Support"
export XDG_CONFIG_DIRS="$HOME/Library/Preferences"
export XDG_CONFIG_DIRS="/Library/Application Support:$XDG_CONFIG_DIRS"
export XDG_CONFIG_DIRS="/Library/Preferences:$XDG_CONFIG_DIRS"


# default editor
export EDITOR=/usr/local/bin/code
export VISUAL=/usr/local/bin/code

# zsh and oh-my-zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZSH="$XDG_DATA_HOME/oh-my-zsh"
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump-${ZSH_VERSION}"
export SHELL_SESSIONS_DISABLE=1

# gpg for git commit signing
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GPG_TTY="$(tty)"

source "$ZDOTDIR/env_vars"
