# theme
ZSH_THEME="common"

# plugins
plugins=(
    colored-man-pages # adds colors to man pages
    macos             # provides a few utilities on macOS
)

# zsh history file
export HISTFILE="$XDG_STATE_HOME/zsh/zsh_history"
# homebrew
export PATH="/usr/local/sbin:$PATH"
# asdf
. "$(brew --prefix asdf)/libexec/asdf.sh"

source "$ZSH/oh-my-zsh.sh"  # oh-my-zsh
source "$ZDOTDIR/aliases"   # aliases
source "$ZDOTDIR/functions" # functions
# syntax highlighting
source "/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
