# theme
ZSH_THEME="common"

# plugins
plugins=(
    colored-man-pages # adds colors to man pages
    macos             # provides a few utilities on macOS
)

# zsh history file
export HISTFILE="$XDG_STATE_HOME/zsh/zsh_history"
# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
# asdf
. "$(brew --prefix asdf)/libexec/asdf.sh"

source "$ZSH/oh-my-zsh.sh"  # oh-my-zsh
source "$ZDOTDIR/aliases"   # aliases
source "$ZDOTDIR/functions" # functions
# syntax highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
