# Environment: Raspberry Pi
# =============================================================================

# global environment variables
source $(realpath "$(readlink "$HOME/.zshenv")/../../../../config/zshenv")

# machine specific environment variables
export TAILSCALE_DOMAIN="rpi.tail2a477.ts.net"
