# Environment: Raspberry Pi
# =============================================================================

# global environment variables
config="$(dirname "$(realpath "$(readlink "$HOME/.zshenv")")")"
source "$config/../../../config/zshenv" # rpi -> machines -> machine
unset config

# machine specific environment variables
export TAILSCALE_DOMAIN="rpi.tail2a477.ts.net"
